# Generated by Django 3.1.5 on 2021-01-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletickets',
            options={'verbose_name': 'Доступные билеты', 'verbose_name_plural': 'Доступные билеты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'События', 'verbose_name_plural': 'Cобытия'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билеты', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelOptions(
            name='userregistrationinfo',
            options={'verbose_name': 'Информация о полдьзователе', 'verbose_name_plural': 'Информация о пользователе'},
        ),
        migrations.AlterModelOptions(
            name='usersessions',
            options={'verbose_name': 'Пользовательская сессия', 'verbose_name_plural': 'Пользовательская сессия'},
        ),
        migrations.AlterModelOptions(
            name='usertickets',
            options={'verbose_name': 'Пользовательский билет', 'verbose_name_plural': 'Пользовательский билет'},
        ),
    ]
