# Generated by Django 3.1.5 on 2021-01-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0002_auto_20210109_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertickets',
            options={'verbose_name': 'Пользовательский билет', 'verbose_name_plural': 'ользовательский билет'},
        ),
    ]
