# Generated by Django 3.1.5 on 2021-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0004_auto_20210109_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletickets',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
