# Generated by Django 3.1.5 on 2021-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0005_auto_20210109_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usertickets',
            name='ticket_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usertickets',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
